# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 17:11
from __future__ import unicode_literals

import accounts.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upload',
            field=models.FileField(upload_to=b'uploaded_files/', validators=[accounts.validation.validate_file_extension]),
        ),
    ]
